name: commit-rules

env:
  DATABASE_URL: file:./dev.db

on: []

jobs: 
  Node-Setup:
    runs-on: ubuntu-latest
    steps:
      - run: cd backend
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm install --force
      - run: npm run eslint
      - run: npm run prisma
      - run: npm run test